services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: trackly-backend
    ports:
      - "3000:8001"
    networks:
      - together-network
    volumes:
      - ./backend/configs:/app/configs
      - ./backend/storage:/app/storage

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: trackly-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:8002"
    depends_on:
      - backend
    networks:
      - together-network

networks:
  together-network:
    external: true
